name: Deploy to n8n
on:
  push:
    paths:
      - 'workflows/sehaty.json'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Upsert workflow in n8n
        env:
          N8N_URL: ${{ secrets.N8N_URL }}        # e.g., http://localhost:5678
          N8N_API_KEY: ${{ secrets.N8N_API_KEY }} # n8n personal access token
        run: |
          set -eo pipefail
          WF_FILE="workflows/sehaty.json"
          NAME=$(jq -r '.name' "$WF_FILE")

          EXIST=$(curl -sS --fail \
            -H "X-N8N-API-KEY: $N8N_API_KEY" \
            "$N8N_URL/api/v1/workflows?filter[name]=$NAME")
          WF_ID=$(echo "$EXIST" | jq -r '.[0].id // empty')

          if [ -z "$WF_ID" ] || [ "$WF_ID" = "null" ]; then
            echo "Creating new workflow: $NAME"
            curl -sS --fail -X POST "$N8N_URL/api/v1/workflows" \
              -H "Content-Type: application/json" \
              -H "X-N8N-API-KEY: $N8N_API_KEY" \
              --data @"$WF_FILE"
          else
            echo "Updating workflow id=$WF_ID name=$NAME"
            curl -sS --fail -X PUT "$N8N_URL/api/v1/workflows/$WF_ID" \
              -H "Content-Type: application/json" \
              -H "X-N8N-API-KEY: $N8N_API_KEY" \
              --data @"$WF_FILE"
          fi
